---
name: "Deploy to SiteGround (Production)"
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Build Vite app
        run: npm run build

      - name: Setup SSH key
        env:
          SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_KEY" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -p 18765 ssh.inkfinit.com >> ~/.ssh/known_hosts

      - name: Deploy via rsync
        run: |
          echo "🚀 Deploying to SiteGround PRODUCTION..."
          rsync -avz --delete -e "ssh -p 18765 -o StrictHostKeyChecking=no" \
            dist/ \
            u2050-grkr3li1rvfx@ssh.inkfinit.com:/home/customer/www/inkfinit.com/public_html/
          echo "✅ Deployment complete on production."

      - name: Send deployment email (via SiteGround)
        run: |
          ssh -i ~/.ssh/id_ed25519 -p 18765 -o StrictHostKeyChecking=no \
            u2050-grkr3li1rvfx@ssh.inkfinit.com "php -r '
              $to=\"debug@inkfinit.com\";
              $sub=\"✅ Inkfinit PRODUCTION Deployed (\".date(\"Y-m-d H:i:s\").\")\";
              $msg=\"Deployment completed successfully on PRODUCTION at \".date(\"r\").\"\\nBranch: main\\nURL: https://inkfinit.com\";
              mail(\$to, \$sub, \$msg, \"From: Inkfinit CI/CD <noreply@inkfinit.com>\");
            '"
          echo "📨 Email sent from SiteGround server."

      - name: Done
        run: echo "✅ Production deploy complete at $(date)"
