name: Deploy to SiteGround (Production)
on:
  push:
    branches: [ "main" ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm run build
      - run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
      - run: |
          rsync -az --delete -e "ssh -p 18766 -o StrictHostKeyChecking=no -i ~/.ssh/id_ed25519" \
          dist/ u2050-grkr3li1rvfx@ssh.inkfinit.com:/home/customer/www/inkfinit.com/public_html/
          echo "✅ Production deploy complete."
      - run: |
          ssh -i ~/.ssh/id_ed25519 -p 18766 -o StrictHostKeyChecking=no \
          u2050-grkr3li1rvfx@ssh.inkfinit.com \
          "php -r 'mail(\"debug@inkfinit.com\",\"Production Deploy ✅\",\"Deployment succeeded on $(date)\",\"From: Inkfinit CI/CD <noreply@inkfinit.com>\");'"
          echo "📨 Email sent successfully."
      - run: echo "✅ CI/CD production complete."
